# Generated by Django 5.0.4 on 2024-05-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('DoktorID', models.AutoField(primary_key=True, serialize=False)),
                ('KullaniciAdi', models.CharField(max_length=100, null=True, unique=True)),
                ('Ad', models.CharField(max_length=100)),
                ('Soyad', models.CharField(max_length=100)),
                ('UzmanlikAlani', models.CharField(max_length=100)),
                ('CalistigiHastane', models.CharField(max_length=255)),
                ('Sifre', models.CharField(default='sifre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('HastaID', models.AutoField(primary_key=True, serialize=False)),
                ('KullaniciAdi', models.CharField(max_length=100, null=True, unique=True)),
                ('Ad', models.CharField(max_length=100)),
                ('Soyad', models.CharField(max_length=100)),
                ('DogumTarihi', models.DateField()),
                ('Cinsiyet', models.CharField(max_length=10)),
                ('Telefon', models.CharField(max_length=50)),
                ('Adres', models.CharField(max_length=255)),
                ('Sifre', models.CharField(default='sifre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('YoneticiID', models.AutoField(primary_key=True, serialize=False)),
                ('KullaniciAdi', models.CharField(max_length=100, null=True, unique=True)),
                ('Sifre', models.CharField(default='sifre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('randevu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilkUygulama.doktor')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilkUygulama.hasta')),
            ],
        ),
    ]
