# Generated by Django 5.0.4 on 2024-05-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkUygulama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TıbbiRapor',
            fields=[
                ('RaporID', models.AutoField(primary_key=True, serialize=False)),
                ('RaporTarihi', models.DateField()),
                ('RaporIcerigi', models.TextField()),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tibbi_raporlar', to='ilkUygulama.hasta')),
            ],
        ),
    ]
