# Generated by Django 5.0.4 on 2024-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkUygulama', '0002_tıbbirapor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tıbbirapor',
            name='URL',
            field=models.CharField(default='', max_length=200),
        ),
    ]
